image: node:alpine
stages:
  - lint
  - test
  - deploy

cache:
  paths:
  - node_modules/

lint:
  stage: lint
  tags:
    - docker
  variables:
    NODE_ENV: 'development'
  script:
    - npm install --silent
    - npm run lint

test:
  image: node:alpine
  stage: test
  tags:
    - docker
  variables:
    NODE_ENV: 'development'
  script:
    - npm install --silent
    - npm run test

deploy staging:
  image: tmaier/dpl
  type: deploy
  stage: deploy
  tags:
    - heroku
  only:
    - master
  environment:
    name: stageing
    url: https://laundry-company.herokuapp.com
  script:
    - dpl --provider=heroku --app=laundry-company --api-key=$HEROKU_API_KEY
